config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check



  # Pour les chats (nested dans trips) :
  # GET /trips/:trip_id/chats - Liste les chats d'un voyage
  # GET /trips/:trip_id/chats/new - Nouveau chat pour ce voyage
  # POST /trips/:trip_id/chats - Créer un chat pour ce voyage

  # ils nous faut des routes chats :
  # /chats post create
  # /chats/:id  get show
  resources :trips do
    resources :chats, only: [:create]
  end

  # chats (en dehors du nesting pour show /edit/upate/destroy)
  resources :chats, only: [:index, :show, :destroy] do
    resources :messages, only: [:create]
  end

  # pages
  get "profile", to: "pages#profile"
  # get "home", to: "pages#home" # on peut ne pas le faire, et landing to connect direct

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to "https://github.com/EileenYeh/AI_TRAVEL_ASSISTANT", target: "_blank", class: "footer-icon" do %>
      <i class="fab fa-github"></i>
    <% end %>
  </div>

  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-sm navbar-light navbar-lewagon" px-6>
  <div class="container-fluid">
    <%= link_to trips_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item" >
            <%= link_to "Home", trips_path, class: "nav-link" %>
          </li>
          <%# ajout de link to pour chats_path (besoin d'index en conséquent)%>
          <li class="nav-item" >
            <%= link_to "Mon assistant IA ", chats_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown" >
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidenav.html.erb
<ul class="position-sticky sticky-top nav flex-column">
  <li class="nav-item">
    <%= link_to "#",
          class: "nav-link text-dark",
          data: { action: "click->toggle#call", toggle_target: "hide" } do %> <%# data-action ici%>
      <i class="fa-regular fa-square-caret-left"></i>
    <% end %>
  </li>

  <% trips.each do |trip| %>
    <li class="nav-item">
      <%= link_to trip.destination, trip_path(trip), class: "nav-link text-dark" %>
    </li>
  <% end %>
</ul>